apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: isodate-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: isodate-service
    spec:
      containers:
      - name: isodate-service
        image: eu.gcr.io/david-on-microservices/isodate-service:latest
        ports:
        - containerPort: 3000
