apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: utcdate-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: utcdate-service
    spec:
      containers:
      - name: utcdate-service
        image: {{ .Values.images.utcdate }}
        ports:
        - containerPort: 3001
